[package]
name = "telegrambot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telebot = "0.3.0"
futures = "0.1.0"
reqwest = "0.10.4"
select = "0.4.0"
